branches:
only:
  - master
language: python
python:
  - '2.7'
  - '3.4'
install:
  - pip install -r requirements.txt
  - python setup.py install
after_success: coveralls
sudo: false
install: "pip install -r requirements.txt"
script: nosetests --with-coverage --cover-package=parserator